core_files:
    # Core utilities and configuration
  - path: src/common/auth.py
    description: decorators for web request auth
  - path: src/common/navigation.py
    description: decorators to register pages for sitemap etc
  - path: src/common/domain_config.py
  - path: src/common/logging_config.py
  - path: src/common/user_config.py
  - path: src/constants.py

    # base database info
  - path: src/common/database.py
    description: Database connection management
  - path: src/common/models.py
    description: SQLAlchemy models

    # Parser - headers only
  - path: src/parser/colorblocks.py
    description: HTML generation for various tags
  - path: src/parser/lexer.py
    description: Lexing of input text
    header_only: true
  - path: src/parser/parser.py
    description: AST parsing
    header_only: true
  - path: src/parser/html_generator.py 
    description: HTML output generation
    header_only: true
    
    # API integrations
  - path: src/common/openai_client.py
    header_only: true
  - path: src/common/telemetry.py
    header_only: true
    
    # Channel management
  - path: src/common/channel_config.py
  - path: src/common/messages.py
    header_only: true

    # Web server
  - path: src/web/server.py

templates:
  # Core CSS files
  - path: src/web/css/common.css
  - path: src/web/css/atacama.css

  # Core JS files
  - path: src/web/js/atacama.js

  # Additional HTML/CSS
  - path: src/web/templates/chain.html
  - path: src/web/templates/message.html
  - path: src/web/templates/stream.html
  - path: src/web/templates/submit.html
  - path: src/web/css/stream.css
  - path: src/web/css/submit.css
  - path: src/web/css/chess.css
