"""add parent id and annotations

Revision ID: 50ae0061f204
Revises: 
Create Date: 2024-12-23 19:45:44.658327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ae0061f204'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails') as batch_op:
        op.add_column('emails', sa.Column('parent_id', sa.Integer(), nullable=True))
        op.add_column('emails', sa.Column('chinese_annotations', sa.Text(), nullable=True))
        op.add_column('emails', sa.Column('llm_annotations', sa.Text(), nullable=True))
        op.alter_column('emails', 'content',
                   existing_type=sa.TEXT(),
                   nullable=False)
        op.alter_column('emails', 'processed_content',
                   existing_type=sa.TEXT(),
                   nullable=False)
        op.alter_column('emails', 'created_at',
                   existing_type=sa.DATETIME(),
                   nullable=False)
        op.create_foreign_key(None, 'emails', 'emails', ['parent_id'], ['id'])
        # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails') as batch_op:
        op.drop_constraint(None, 'emails', type_='foreignkey')
        op.alter_column('emails', 'created_at',
                   existing_type=sa.DATETIME(),
                   nullable=True)
        op.alter_column('emails', 'processed_content',
                   existing_type=sa.TEXT(),
                   nullable=True)
        op.alter_column('emails', 'content',
                   existing_type=sa.TEXT(),
                   nullable=True)
        op.drop_column('emails', 'llm_annotations')
        op.drop_column('emails', 'chinese_annotations')
        op.drop_column('emails', 'parent_id')
        # ### end Alembic commands ###
