"""Add quote type

Revision ID: b9e29fbf2815
Revises: 50ae0061f204
Create Date: 2024-12-24 18:46:45.037278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9e29fbf2815'
down_revision: Union[str, None] = '50ae0061f204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('quote_type', sa.String(), nullable=True))
    op.add_column('quotes', sa.Column('commentary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotes', 'commentary')
    op.drop_column('quotes', 'quote_type')
    # ### end Alembic commands ###
