# Atacama Channel Configuration

[channels]
# Default internal channel
private = { description = "Default private channel", access_level = "private" }
sandbox = { description = "For testing and experimentation", access_level = "private" }

# Public channels
sports = { description = "Sports discussion", access_level = "public" }
politics = { 
    description = "Political discussion", 
    access_level = "restricted",
    domain_restriction = "@earlyversion.com",
    requires_preference = true
}
religion = { description = "Religious discussion", access_level = "public" }
chess = { description = "Chess discussion and games", access_level = "public" }
books = { description = "Book discussion and reviews", access_level = "public" }
television = { description = "TV shows and media", access_level = "public" }
tech = { description = "Technology discussion", access_level = "public" }
llm = { description = "Language model discussion", access_level = "public" }
misc = { description = "Miscellaneous topics", access_level = "public" }

[defaults]
# Default channel for new messages
default_channel = "private"

# Default channel preferences for new users
default_preferences = [
    "sports",
    "religion",
    "books",
    "television",
    "tech",
    "llm",
    "misc"
]
